riasvdv/statamic-redirect

- resources/js/components/DeletesListingRow.js
Not sure if this is the right way to fix this issue, but since `this.rows` is unassigned, we can maybe use `this.items` instead in `DeletesListingRow.js`.
> Fixes riasvdv/statamic-redirect#13

- src/UpdateScripts/ClearErrors.php
At the end of `composer update`, one of this addon's upgrade scripts ran and caused this error:
I had a look and it was as simple as using the Illuminate File facade, rather than Statamic's File facade. I would have presumed Statamic's one would just inherit the Illuminate one but it doesn't look like it 🤷‍♂️
> Fix error when updating addon

- src/RedirectServiceProvider.php
In the current version ([1.10.3](https://github.com/riasvdv/statamic-redirect/releases/tag/1.10.3)), I attempted to run the database migrations after publishing the necessary migration stubs. In doing so, I received the following error:
```php
Whoops\Exception\ErrorException
Cannot declare class CreateRedirectTables, because the name is already in use
at database/migrations/2022_01_19_142039_create_settings_table.php:7
3▕ use Illuminate\Database\Migrations\Migration;
4▕ use Illuminate\Database\Schema\Blueprint;
5▕ use Illuminate\Support\Facades\Schema;
6▕
➜   7▕ class CreateRedirectTables extends Migration
8▕ {
9▕     public function up()
10▕     {
11▕         Schema::create('redirects', function (Blueprint $table): void {
+1 vendor frames
2   [internal]:0
Whoops\Run::handleShutdown()
``` …
> Changes the name of the redirect table migration to clear re-declaration error

- database/migrations/create_redirect_tables.php.stub
Changed the migration to make `lastSeenAt` & `timestamp` into integers. The reason is that mysql timestamps aren't unix timestamps.
This should fix issue #52
> Changed migration to set lastSeenAt and timestamp as integer

- .github/workflows/run-tests.yml
- .gitignore
- composer.json
- src/Controllers/ImportRedirectsController.php
- src/Data/Concerns/TracksQueriedRelations.php
- src/Data/Redirect.php
Changes:
- Updated Github workflow with Statamic 3.2 & Laravel 7/8 tests
- Updated `composer.json` to allow PHP 7.4 and Statamic 3.2 - also bumped `spatie/simple-excel` to latest supported verison for PHP 7.4
- Updated `.gitignore`
- Minor adjustments to file extension detection for import
- Backported `Statamic\Data\TracksQueriedRelations` to support Statamic 3.2
> Re-added support for Statamic 3.2

- src/RedirectServiceProvider.php
This pull request fixes #83 by adding `MoveRedirectsToDefaultSite` to the list of registered upgrade scripts for this addon. If an upgrade script isn't registered, it won't be used.
> Add MoveRedirectsToDefaultSite to the array of upgrade scripts

- src/Listeners/CacheOldUri.php
- src/Listeners/CreateRedirect.php
Hi
I'm using your addon in a project with over 5000 entries in multiple collections. As we use Statamic only headless, we only need the manage aspect of this addon and all the rest should be disabled.
In my case, redirects would be deleted but not be recreated (I want none of these two features).
As there is an option to disable the whole thing, I think that the Listeners also should respect this configuration.
This is what this PR does.
> Respect enable config

- src/RedirectServiceProvider.php
This pull request makes a small improvement - it adds labels to the permissions added by this addon. Instead of them all being lowercase in the CP, they're a bit friendlier:
> Add labels to permissions

- src/Http/Middleware/HandleNotFound.php
Resolved error with steamed response: 
```
Error: Call to undefined method Symfony\Component\HttpFoundation\StreamedResponse::status()
```
Resolved #140
> Support symfony http foundation steamed response

- config/redirect.php
- database/migrations/create_eloquent_redirect_table.php.stub
- src/Contracts/Redirect.php
- src/Contracts/RedirectQueryBuilder.php
- src/Contracts/RedirectRepository.php
- src/Controllers/Api/RedirectController.php
- src/Controllers/ImportRedirectsController.php
- src/Controllers/RedirectController.php
- src/Data/Redirect.php
- src/Eloquent/Redirects/RedirectModel.php
- src/Eloquent/Redirects/RedirectQueryBuilder.php
- src/Eloquent/Redirects/RedirectRepository.php
- src/Exporters/CsvExporter.php
- src/Exporters/JsonExporter.php
- src/Facades/Redirect.php
- src/Http/Middleware/HandleNotFound.php
- src/Listeners/CreateRedirect.php
- src/RedirectServiceProvider.php
- src/Stache/Redirects/RedirectQueryBuilder.php
- src/Stache/Redirects/RedirectRepository.php
- src/Stache/Redirects/RedirectStore.php
- tests/Feature/Controllers/ImportRedirectsControllerTest.php
- tests/Feature/Middleware/HandleNotFoundTest.php
- tests/Feature/MoveRedirectsToDefaultSiteTest.php
- tests/Feature/RedirectTest.php
- tests/TestCase.php
This PR adds eloquent support to the redirects.
To do this I've:
- Moved any calls to Data\Redirect to a facade (Facades\Redirect)
- Created a repository contract and query builder contract
- Created a stache repository and moved the save/delete/query/find methods from Data\Redirect to it
- Created eloquent repositories
Let me know if you need/want anything else to have this approved.
Closes https://github.com/riasvdv/statamic-redirect/issues/106
> Switch to using a repository & facade for Redirect, add eloquent support

- resources/views/widgets/errors.blade.php
The dashboard shows the following error when using the error-widget:
This PR solves this for us.
> Fix date error on error widget

- resources/js/components/ErrorsListing.vue
- resources/views/widgets/errors.blade.php
The 'Handled" dot on the error index page is currently not visible.
This PR solves this and makes the dot more consistent with the error widget.
> Fix handled dot indicator

- database/migrations/create_eloquent_redirect_table.php.stub
- src/Blueprints/RedirectBlueprint.php
- src/Eloquent/Redirects/RedirectRepository.php
- src/RedirectServiceProvider.php
- src/UpdateScripts/RenameLocaleToSiteOnRedirectsTable.php
Advantages:
* More consistent with [statamic/eloquent-driver](https://github.com/statamic/eloquent-driver/tree/master).
* Fixes issue where eloquent-redirect could not be created because of validation rule in blueprint which queries based on a [`site` column](https://github.com/riasvdv/statamic-redirect/blob/09f32894f1accf8c7c0373f18298936a6d49f023/src/Blueprints/RedirectBlueprint.php#L29C69-L29C69).
* Fixes issue when using eloquent redirects with multisite. The multisite filter on the index-page expects a `site` column.
> Rename `locale` to `site` on redirects table

- src/Eloquent/Redirects/RedirectRepository.php
`toModel()` currently uses `firstOrNew` to turn a redirect data-object into a model. 
However, `firstOrNew` does not update the `first` object with the updated properties. Instead, it just returns the outdated model. Which is why you currently can not update eloquent redirects.
> Fix eloquent redirects not updating

- src/Blueprints/RedirectBlueprint.php
Redirect columns are currently not added by default:
This causes the "source" column to display at the end.
This PR fixes this by setting `listable` to true on all fields inside the blueprint.
> Make redirect fields listable by default

- resources/js/components/Publish/PublishForm.vue
Removes the `resource` prop which is a leftover from Runaway.
> Cleanup publish form

- DOCUMENTATION.md
The [documentation page](https://statamic.com/addons/rias/redirect/docs) on statamic.com does not get the `[!NOTE]` I added in a previous PR.
> Remove Github note markdown

- database/migrations/create_redirect_redirects_table.php.stub
When using `char` in the migration of the `redirects` table, the resulting schema in postgres is using `bpchar(10)` as datatype, which gets padded with spaces. Those spaces are not removed by default, which means the redirects can not be resolved correctly from the database (e.g. `'regex     ' === 'regex'` in `Redirect::findByUrl`).
The resulting datatype in mysql (`char(10)`) gets also padded, but by default the trailing spaces are removed when the value is retrieved from the database. Therefore the problem described above do not arise when using mysql.
However, when using `string` in the migration, the redirects work with both database management systems.
See also:
- https://www.postgresql.org/docs/current/datatype-character.html 
- https://dev.mysql.com/doc/refman/8.0/en/char.html
> change datatype in migration so unpadded datatypes are used in db

- config/redirect.php
- database/migrations/add_description_to_redirect_redirects_table.php.stub
- src/Blueprints/RedirectBlueprint.php
- src/Controllers/RedirectController.php
- src/Data/Redirect.php
- src/Eloquent/Redirects/RedirectRepository.php
- src/Http/Resources/ListedRedirect.php
- src/RedirectServiceProvider.php
Hi @riasvdv!
First of all, thank you for this great package, it's exactly what we needed!
Well, *almost* exactly 😉 While implementing we realized we're missing the following two functionalities:
1. Adding a description to a redirect, which could be a name, a date, etc. Our client needed something like that, purely for internal use, and we figured that it may also benefit others!
* I have also added a new migration for this, hopefully that aligns with how you would see it.
2. Setting the default redirect type. Currently it's always `302`, but our client needs it to be `301`. This is also something we figured might be interesting for others.
* I have changed the type from `string` to `int`, as otherwise the dropdown wouldn't get filled correctly!
If you have any questions, or if you would …
> Redirect description & default redirect type

- src/Http/Middleware/HandleNotFound.php
- tests/Feature/Middleware/HandleNotFoundTest.php
> Merge query params instead of just appending them

- src/UpdateScripts/AddDescriptionColumnToRedirectsTable.php
Hi @riasvdv,
Appreciate the quick processing of my previous PR! I have noticed one small bug in the update script, which I fixed in this PR. Basically, when the `redirect_connection` is set to `default`, it would look for the schema connection `default`, which doesn't exist in the config. I corrected it to be in line with others of such statements in your package!
> Use correct database connection

- src/Http/Middleware/HandleNotFound.php
- tests/Feature/Middleware/HandleNotFoundTest.php
Unfortunately I was introducing a bug when fixing https://github.com/riasvdv/statamic-redirect/pull/202
Problems arise when the destination's url has no `path` part, since `$destination_parsed['path']` is then undefined (see line 163).
Now I have added some tests for this case and made sure it also works for destinations without `path` part.
At the same time the `fragment` part of the destination URL is kept - as it was discarded until now.
> fix query parameter merging for urls without path part (respecting fragment part)

- .github/workflows/run-tests.yml
- .gitignore
- composer.json
- database/migrations/increase_redirect_error_table_url_length.php.stub
- database/migrations/increase_redirect_redirects_table_url_length.php.stub
- src/Data/Error.php
- src/Data/Redirect.php
- src/RedirectServiceProvider.php
- src/Stache/Redirects/RedirectRepository.php
- src/UpdateScripts/AddDescriptionColumnToRedirectsTable.php
- src/UpdateScripts/IncreaseUrlSizeOnErrors.php
- src/UpdateScripts/IncreaseUrlSizeOnRedirects.php
- tests/TestCase.php
Since some of our redirects contain some large query parameters, we would like the URL field limit to be increased to 2048 characters (this is a generally agreed upon limit, although no exact limit has been defined nor enforced).
Since column indexes only work for columns up to 255 characters, I have added an additional MD5 hashed column.
Since a MD5 hash is always 32 characters long, this can be indexed and should be decently unique.
I have adjusted the queries to use this new indexed column, so the speed of these queries should be similar to how they were.
The queries will still ensure the actual URL matches, since there is still a chance for different URLs to have the same MD5 hash.
I also noticed that when publishing the migrations of the plugin, they are ordered alphabetically, which …
> Support URLs up to 2048 characters

- .gitignore
- src/Blueprints/RedirectBlueprint.php
- src/Controllers/ImportRedirectsController.php
- src/Controllers/RedirectController.php
- src/Data/Redirect.php
- src/Eloquent/Redirects/RedirectRepository.php
- src/Http/Filters/RedirectSite.php
- src/Http/Middleware/HandleNotFound.php
- src/Listeners/CreateRedirect.php
- src/Rules/SourceIsNotRedirected.php
- src/Stache/Redirects/RedirectRepository.php
- src/Stache/Redirects/RedirectStore.php
- tests/Feature/Middleware/HandleNotFoundTest.php
Closes #186
Closes #200
Covers #118, but does not close it:
I added a site column to the index, a site selector to the blueprint and made the site filter on the index work as expected.
The UI can still be further improved by allowing easily duplicating a redirect from one site to another (like with entries), but I can't figure out how to get this working, so maybe someone with more experience in this can look into implementing that.
Another option would be to make the site selection multi-select, but this does not currently align with the DB so then it would be necessary to look into migrating this data properly.
- Used `site` instead of `locale`
_Statamic has since switched over, best for the plugin to follow this new implementation_
- Created separate `SourceIsNotRedirected` rule object …
> Multi-site improvements

- src/Exporters/CsvExporter.php
- src/Exporters/JsonExporter.php
This pull request ensures that the `$request->site()` value is handled as a string (the site handle), rather than as a `Site` object.
As shown in the implementation:
- [`$site` is stored as a string handle](https://github.com/riasvdv/statamic-redirect/blob/76e2b9d122c79aefbf1b0b38fccfbaa6a64450c9/src/Data/Redirect.php#L40-L41)
- [`$site` is the string handle of a Statamic Site](https://github.com/riasvdv/statamic-redirect/blob/main/src/Data/Redirect.php#L100)
Fixes #216
> fix: correctly handle site property as string when exporting
